title: "She's An Asset"
description: "Empowering women to lead with confidence, boundaries, and real strength. Women's safety workshops, corporate training, and leadership development."
contact_email: "support@shesanasset.com"
social:
  instagram: "https://instagram.com/shesanasset"
  linkedin: "https://linkedin.com/in/autumn-shesanasset"
  youtube: "https://youtube.com/@shesanasset"
  twitter: ""
footer_text: "Empowering women to lead with confidence, clarity, and real strength."

